sudo: false
language: node_js

node_js:
  - "8"
  - "9"
os:
  - linux
  - osx

before_install:
  - npm install -g istanbul coveralls
  - npm install -g mocha typescript

before_script:
  - npm install -g codeclimate-test-reporter

after_success:
  - make test-cov

script:
  - npm test

addons:
  code_climate:
    repo_token: 03272f5fe6896aa399500eceb1733227dd869a227837ace3c7ee005cacf4aebc

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/4d51130aaea652dbc8f1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
